### ISSUE TITLE
Installing addon from the `repository-beta` installs version 2.21 instead of up-to-date one 

### ISSUE THREAD

**Issue by primeroz** [hassio-addons/addon-prometheus#50] opened 2022-07-27 17:09 UTC
I installed the addon by adding the https://github.com/hassio-addons/repository-beta since is not available in the stable one

I am getting the version 2.21 of prometheus installed though rather than latest one pushed to this addon 2.36.1 

Am i doing something wrong ?

**Comment by zonorti** [comment] 2022-10-03 11:55
That repository references a [docker image](https://github.com/hassio-addons/repository-beta/blob/master/prometheus/config.json#L33), if you want to install main - you can go with cloning this repo into /addons and installing it as a local addon.
I had problems building it before I removed pinned python related versions from the Dockerfile.

**Comment by frenck** [comment] 2022-10-03 11:58
Feel free to submit a PR to bump version or anything else.
I'm closing this issue, as it is a request, not a bug report.

**Closed by frenck** 2022-10-03 11:58 UTC

**Comment by primeroz** [comment] 2022-10-03 12:18
I opened it as a bug because i thought the reference image `https://github.com/hassio-addons/addon-prometheus/tree/main/prometheus` was going to be pulled in , and in that repo the version is 2.36.1  but i guess it actually pulls the version defined in https://github.com/hassio-addons/repository-beta/blob/master/prometheus/config.json#L3 

I will see to understand how it works and create a PR 

thanks
